### ISSUE TITLE
URL in Github Project seems to be wrong

### ISSUE THREAD

**Issue by Stummi** [rsercano/mongoclient#565]
The project lists https://www.nosqlclient.com/ as its project URL on github. 

When I follow this Link I get a SSL Cert issue. When I ignore the SSL cert issue I get redirected to some game in the apple app store

**Comment by rsercano** [comment]
Oh thanks for letting me know @Stummi I'm not sure what happened on there, we're no longer developing nosqlclient hence website was offline. 

I'll check that! Thanks!
